spring.application.name=playerdatatracking

# Configuracion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/playerdata
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#XSLImpostPath
xsl.path = classpath:xsl/Scouting.xlsx

#ApiKey
apikeys.secret = dUq1uvQIAl8eevnjToANcMGfrRbyW65mfaAOa2AwSMU=

logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=ERROR


# Tiempo de inactividad para expirar sesi�n (ej. 30 min)
server.servlet.session.timeout=30m

# Cookie de sesi�n
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
# En desarrollo local sin HTTPS puedes dejar secure=false; en prod ponlo en true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=LAX

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
spring.session.timeout=30m

spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

# Directorios de almacenamiento de JSONs descargados de la API
# Cambiar a rutas absolutas al externalizar la aplicación (p.ej. /data/players/ o C:/data/players/)
players.json.directory=src/main/resources/json/apiFotball/players/
leagues.json.directory=src/main/resources/json/apiFotball/leagues/